branches:
  only:
    - master

language: android
sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - doc-25

before_install:
    - pip install --user codecov
    - wget -P lib/ https://parseonbuddy.blob.core.windows.net/ppns/ppns-android-1.0.jar
#    - mvn validate

script:
  - ./gradlew clean testDebugUnitTest jacocoTestReport --info

after_success:
#  - ./gradlew coveralls
  - codecov
# - ./scripts/publish_snapshot.sh

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    all_branches: true
#   branch: master
    tags: true
