branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/ # regex
    - travis1

language: android
sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - doc-26

before_install:
    - pip install --user codecov
    - wget -P ./Parse/lib/ https://parseonbuddy.blob.core.windows.net/ppns/ppns-android-1.0.jar
#    - mvn validate

script:
  - ./gradlew clean testDebugUnitTest jacocoTestReport

after_success:
#  - ./gradlew coveralls
  - codecov
# - ./scripts/publish_snapshot.sh

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    all_branches: true
#   branch: master
    tags: false
